### ISSUE TITLE
Viewing docs offline

### ISSUE THREAD

**Issue by kennymalac** [apache/echarts-doc#133]
Hello, I am just about to take airplane flight today. I wanted to checkout this project to be able to use docs offline.
However, in this commit I see core libraries are using CDN : https://github.com/apache/incubator-echarts-doc/commit/9db41c656f837bb1bdb4ede77074a51c67fb29aa

Anyway to make this by configuration so we can use the docs offline? 

Thanks

**Comment by plainheart** [comment]
Hi, there is a CLI tool [echarts-offline-doc-cli](https://github.com/plainheart/echarts-offline-doc-cli) for building or downloading offline documentation. You can take a try if you like.
