### ISSUE TITLE
官网文档建议

### ISSUE THREAD

**Issue by yang201806** [apache/echarts-doc#168]
有些属性，如：series-line. endLabel 没有写版本支持，希望得到完善。（这里只说了一个例子，相信还有其它的）链接：https://echarts.apache.org/zh/option.html#series-line.endLabel

**Comment by pissang** [comment]
https://github.com/apache/echarts-doc/commit/12c6e0925d4fc9de21e48d82b785b1e19df869de 中已修正

**Comment by yang201806** [comment]
谢谢，但是在官网文档上还看不到啊

**Comment by yang201806** [comment]
谢谢，但是在官网文档上还看不到啊

**Comment by susiwen8** [comment]
还没上线。请稍等
