### ISSUE TITLE
Contribute to options documentation

### ISSUE THREAD

**Issue by ataft** [apache/echarts-doc#188]
Is there a way for me to contribute to the options documentation? For example, in the screenshot below, you can see that the "label.position" for bar charts has the proper "uiControl" setting from the [option.series-bar.js](https://echarts.apache.org/en/documents/option-parts/option.series-bar.js?7cec8ec389) file. However, the "uiControl" is missing for pie charts and I'd like to add it. There are a lot of errors and missing items that I come across and would love to contribute.

![image](https://user-images.githubusercontent.com/11670864/122622333-2cf14280-d04d-11eb-8e74-268ebef2d467.png)

**Comment by susiwen8** [comment]
Sure, this is the repo for Apache ECharts option doc. You can fork it and then make PRs.
