### ISSUE TITLE
[Clarification] Axis Position needs more clarification for onZero

### ISSUE THREAD

**Issue by jiawulin001** [apache/echarts-doc#238]
`axis.position` and `axis.offset` would not work without setting `axis.axisLine.onZero` to false. This can be very confusing for developers. We should add clarification to documentation of axis to help them avoid this.
Please refer to https://github.com/apache/echarts/issues/16783#issuecomment-1084264977

**Comment by pissang** [comment]
@jiawulin001 Thanks for pointing it out. Do you mind creating a PR to add the clarification?

**Comment by jiawulin001** [comment]
Sure, will submit a PR soon.
