### ISSUE TITLE
The "Development" part of README can be improved

### ISSUE THREAD

**Issue by tyn1998** [apache/echarts-doc#291]
Hi guys, I followed the instruction provided in "[Development](https://github.com/apache/echarts-doc#development)" but had trouble in previewing effects after changing some of the docs.

Now I know the solution and I can help to improve README. Please assign this issue to me :)

**Comment by plainheart** [comment]
What trouble did you get into?

**Comment by tyn1998** [comment]
Hi, @plainheart, we talked about the troubles in wechat group so I didn't list them here.

The troubles are due to:

1. Node version
2. browser cache

I have raised a [PR](https://github.com/apache/echarts-doc/pull/292), and in there I add solutions to address certain issues.

**Comment by plainheart** [comment]
For the first issue, if you are using npm `v8.13.x`, please try to downgrade or upgrade to the latest version.
For the second issue, maybe we can use `webpack-dev-server` or `live-server` to do the automatic update after each change.

**Comment by tyn1998** [comment]
Thanks for reply!

> For the first issue, if you are using npm v8.13.x, please try to downgrade or upgrade to the latest version.

I have tried Node v18, v16 and `npm install` fails in both versions but succeeds in v14 (npm v6.14.17).

> For the second issue, maybe we can use webpack-dev-server or live-server to do the automatic update after each change.

HMR is amazing, I really hope this feature can be brought into this doc project!

**Comment by plainheart** [comment]
> I have tried Node v18, v16 and `npm install` fails in both versions but succeeds in v14 (npm v6.14.17).

Could you post the log about the install error?

**Comment by plainheart** [comment]
Just tested the `install` step in various environments and they worked well. Please refer to the following workflow action for details. https://github.com/plainheart/issue-pr-bot-test/actions/runs/3082024906

**Comment by tyn1998** [comment]
@plainheart Thank you for your time!

Maybe the issue is a specific one only occurs on my machine. I will close the issue and the PR.
