### ISSUE TITLE
Get the difference between two versions

### ISSUE THREAD

**Issue by nico-robert** [apache/echarts-doc#307]
Is there a way to get the difference between two versions of Apache ECharts documentation ?
I'm using this library and I would like to know if for example in version 5.4.0 there is any flags that have been added or deleted compared to version 5.2.2 (side documentation)

By example for `title` configuration : `title.id` exists anymore in 5.4.0 ?

**Comment by plainheart** [comment]
If a feature is not supported in old versions, there will be a tip like `Since v5.2.0`. See also https://echarts.apache.org/option.html#series-line.colorBy

**Comment by nico-robert** [comment]
thanks @plainheart, is there a way to know if it is deleted ?

**Comment by nico-robert** [comment]
Can be I could programmatically compare versions... Do you think that would be possible ? I don’t see in this repo (branches/tag) the different versions of ECharts documentation. For example what is the branches/tag  for Echarts `5.2.2` ?

**Comment by plainheart** [comment]
> is there a way to know if it is deleted ?

Generally, an option will only be removed or deprecated in a big version. You can find information from the changelog. 

> Can be I could programmatically compare versions

I'm afraid you can't. Currently, it's hard to do this as some issues with the documentation may be fixed at any time in any version.
