### ISSUE TITLE
Is it possible to know if this option it's required ?

### ISSUE THREAD

**Issue by nico-robert** [apache/echarts-doc#316]
All properties option are not necessary , by example `series-line.id` while `series-line.data` (in almost all cases) is required.
Is there a way to find out in the documentation whether this is required or not?

**Comment by Ovilia** [comment]
Well, I'm afraid not. Because in may cases, some options are required when other options are set to a certain value. So there may not be a field to state if its required or not.

**Comment by nico-robert** [comment]
okay, thanks @Ovilia for the quick response 👍
