### ISSUE TITLE
bmap documentation

### ISSUE THREAD

**Issue by nico-robert** [apache/echarts-doc#322]
In several examples you use `bmap` as option combined with `lines` series. Where can I find the documentation for this? I can’t find it from the official [documentation](https://echarts.apache.org/en/option.html)

**Comment by nico-robert** [comment]
I think I understood, `bmap` is related to the `baidu map` api... Can you confirm ?

**Comment by plainheart** [comment]
Yes, `bmap` is just `Baidu Map`. It's an extension of ECharts and the Chinese version of the documentation is only available at https://github.com/apache/echarts/tree/master/extension-src/bmap. I'm sorry that it doesn't have the English version and I'm worried about the availability of this map service in your area as it's mainly for China. Maybe you can try the [google map extension](https://github.com/plainheart/echarts-extension-gmap) for ECharts if you'd like.

**Comment by nico-robert** [comment]
yes `gmap` for Echarts seems to match with my needs. I will try. Thanks @plainheart.
