### ISSUE TITLE
nameTruncate property is missing in the doc

### ISSUE THREAD

**Issue by nico-robert** [apache/echarts-doc#338]
Hi,
[nameTruncate](https://github.com/apache/echarts/blob/9c4b7423e7cd0727f5f648b720f151885aee53a4/src/coord/axisCommonTypes.ts#L42) is not documented.
It's possible to add this in Apache ECharts documentation...

**Comment by helgasoft** [comment]
> nameTruncate is not documented.

now [it is](https://echarts.apache.org/en/option.html#xAxis.nameTruncate)
