### ISSUE TITLE
Path error problem

### ISSUE THREAD

**Issue by isreturn-ture** [apache/echarts-doc#341]
When starting with server, we can notice that the js and css in the Public file are incorrectly referenced

**Comment by plainheart** [comment]
Could you please provide more information? It's hard to guess what the error is by just one sentence.

**Comment by isreturn-ture** [comment]
路径在没修改之前为../
导致不能正确读取到js与css文件，从而渲染页面



| |
jchz_cn
|
|
***@***.***
|




---- Replied Message ----
| From | Zhongxiang ***@***.***> |
| Date | 04/05/2023 02:41 |
| To | ***@***.***> |
| Cc | return ***@***.***>***@***.***> |
| Subject | Re: [apache/echarts-doc] Path error problem (Issue #341) |

Could you please provide more information? It's hard to guess what the error is by just one sentence.

**Comment by plainheart** [comment]
我这边测试是没有问题的，麻烦抽空贴出一下你是具体如何启动服务器的代码以及控制台报错的信息吧，这样有助于复现问题。
