### ISSUE TITLE
在离线环境下，echarts的图示效果无法显示

### ISSUE THREAD

**Issue by charlessws** [apache/echarts-doc#407]
如题。
必须在yarn dev后，连接互联网的情况下，才能看到图示。不知道是不是项目中使用了CDN。如果是为了离线预览，最好直接就能看到图示。谢谢

**Comment by plainheart** [comment]
此项目是官网文档部分的源码，使用了 CDN，并非专为离线预览。如需离线预览，可以把相关资源下载后，替换相关链接。或者试试 [echarts-offline-doc-cli](https://github.com/plainheart/echarts-offline-doc-cli)。
